version: '3'

services:

  webserver:
    image: nginx:1.19.0
    container_name: webserver
    working_dir: /app 
    
    volumes:
      - .:/app
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /d/www:/mnt/www
      - /d:/mnt/source
   
    ports:
      - "80:80"
      - "443:443"
    networks: 
          - inter   
          - frontend  

  php5:
    build: config/php.5.6
    container_name: php-5
    working_dir: /app
    ports:
      - "9000:9000"
    environment:
        - PMA_HOST=mysql
        - PMA_PORT=3306
        - MYSQL_ROOT_PASSWORD= rootpassword
        - MYSQL_USER= test
        - MYSQL_PASSWORD= test
        - DOCUMENT_ROOT=/app/www
    volumes:
        - .:/app
        - ./config/php.5.6/php-fpm.ini:/usr/local/etc/php/php.ini
        - ./config/php.5.6/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        - /d/www:/mnt/www
        - /d:/mnt/source
    links:
      - mysql
      - mariadb
    networks: 
          - inter   
          - backend

      
  php8:
    build: config/php.8.0
    container_name: php-8
    working_dir: /app

    ports:
      - "9001:9001"
    
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_DB=test_db
      - DOCUMENT_ROOT=/app/www
    volumes:
        - .:/app
        - ./config/php/php-fpm.ini:/usr/local/etc/php/php.ini
        - ./config/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        - /d/www:/mnt/www
        - /d:/mnt/source
    links:
      - mysql
      - mariadb
    networks: 
          - inter   
          - backend

  mysql:
        image: mysql:5.7.35
        container_name: mysql
        working_dir: /app
        volumes:
          - .:/app
        environment:
          - MYSQL_ROOT_PASSWORD=rootpassword
          - MYSQL_DATABASE=test_db
          - MYSQL_USER=test
          - MYSQL_PASSWORD=test
        ports:
          - "3306:3306"
        expose:
          - 3306

        command: mysqld --sql_mode="" --bind-address=0.0.0.0  --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
        restart: on-failure
        networks: 
          - inter   
          - backend    

  mariadb:
        image: mariadb:10.3
        container_name: mariadb
        working_dir: /app
        restart: on-failure
        volumes:
          - .:/app
        environment:
          - MYSQL_ROOT_PASSWORD=rootpassword
          - MYSQL_DATABASE=test_db
          - MYSQL_USER=test
          - MYSQL_PASSWORD=test
        ports:
          - "3307:3306"  
        expose:
          - 3307
        networks: 
          - inter   
          - backend

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
        - 82:80
    environment:
        - PMA_ARBITRARY=1
        - MYSQL_ROOT_PASSWORD=rootpassword
        - MYSQL_DATABASE=test_db
        - MYSQL_USER=test
        - MYSQL_PASSWORD=test
    volumes:
        - /sessions
    networks: 
          - inter   
          - backend
     

  maildev:
        image: djfarrelly/maildev
        container_name: maildev
        ports:
            - 83:80
        networks: 
          - inter   
          - backend

networks: 
  frontend:
    name: "frontend"
    driver: "bridge"
    driver_opts: 
      com.docker.network.bridge.name: "frontend"
    ipam: 
      driver: default
      config: 
        - subnet: 172.25.0.0/16
        
  backend:
    name: "backend"
    driver: "bridge"
    driver_opts:
      com.docker.network.bridge.name: "backend"
    ipam: 
      driver: default
      config: 
        - subnet: 172.21.0.0/16
      
  inter:
    name: "inter"
    driver: "bridge"
    internal: true
    driver_opts:
      com.docker.network.bridge.name: "inter"
    ipam: 
      driver: default
      config: 
        - subnet: 172.23.0.0/16
